databases:
  - name: kovil-fund-db
    plan: free

services:
  - type: web
    name: kovil-fund-app
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kovil-fund-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
