default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: kovil_fund_app_development

test:
  <<: *default
  database: kovil_fund_app_test

production:
  url: <%= ENV["DATABASE_URL"] %>
